### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by mufniarz** [woodrad/irs-990-extract#1]
Matt can you please try waffle.io for this project.  
I'm a bit confused on the directory structure.
I've forked this repository so I can have my own version.  I feel like I upload a directory and it gets removed.

**Comment by woodrad** [comment]
The directory structure is like this.
`lib/`: libraries used by the main program
`test/`: tests and resources for running tests. You will want to check out `test/jasmine/resources` for bits of sample data to test with.
`irs-990-extract.js`: main program
`.eslintrc`: linter configuration
`package.json`: package metadata file.
`gulpfile.js`: configuration file for glup, a js build tool
`.gitignore`: list of files not to be place in version control
`LICENSE`: GPLv3 license file.
`README.md`: readme file for the project.

Things not to be checked into version control: `node_modules`, anything downloaded and placed in `data/`.
