### ISSUE TITLE
Refactor code to be asychnorous and use buffers.

### ISSUE THREAD

**Issue by woodrad** [woodrad/irs-990-extract#2]
Just to hack out the skeleton, I wrote everything as synchronous. Let's refactor this to be more JavaScripty.
This still needs to be addressed.  Specifically within app.js at the moment. --Marcin

**Comment by mufniarz** [comment]
I've modified the source directory.  Modified the functionality to allow the user to pick which process(download, unzip, convert) to perform. We need to modify the test code to test the 'data/' directory with the current code.
